# Default values for flix-server.
# This is a YAML-formatted file.

nameOverride: ""

fullnameOverride: ""


emojiReplicaCount: 1

votebotReplicaCount: 1

votingReplicaCount: 1

webReplicaCount: 1

injectLinkerd:
  enabled: false

# If you have enabled external-dns with your kommander install you can enable automatic DNS registration for your services
externalDNS: 
  enabled: false
  ttl: 
  hostname: 

service:
  enabled: true
